[target.i686-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture i386", 
    "apt-get update && apt-get -y install libssl-dev:i386"
]                 

[target.i686-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture i386", 
    "apt-get update && apt-get -y install libssl-dev:i386"
]                 
# [target.x86_64-unknown-linux-gnu]
# pre-build = [
#     "dpkg --add-architecture amd64", 
#     "apt-get update && apt-get -y install libssl-dev:amd64"
# ]                 
#
# [target.x86_64-unknown-linux-musl]
# pre-build = [
#     "dpkg --add-architecture amd64", 
#     "apt-get update && apt-get -y install libssl-dev:amd64"
# ]                 
#
